version: "3.9"
services:
  client:
    image: node:16-alpine
    user: node
    networks:
      - app-net
    volumes:
      - ./client:/project
    ports:
      - 3000:3000
    working_dir: /project
    entrypoint: sh -c "yarn install && HTTPS=true yarn start"
  server:
    image: python:3-slim-buster
    networks:
      - app-net
    volumes:
      - ./server:/project
      - ./data:/data
    ports:
      - 8000:8000
    working_dir: /project
    entrypoint: bash -c "pip install -r requirements.txt && uvicorn --host=0.0.0.0 --reload app:app"
  cron:
    image: python:3-slim-buster
    volumes:
      - ./cron:/project
      - ./data:/data
    working_dir: /project
    entrypoint: tail -f /dev/null
networks:
  app-net:
