version: "3.9"
services:
  server:
    container_name: server-prod
    image: server-prod
    networks:
      - app-net
    build:
      dockerfile: ./production/server/Dockerfile
      context: .
      target: production
  app:
    container_name: app-prod
    image: app-prod
    networks:
      - app-net
    build:
      dockerfile: ./production/client/Dockerfile
      context: .
      target: production
    ports:
      - 80:80
    depends_on:
      - server
networks:
  app-net: