version: "3.9"
services:
  client:
    image: node:16-alpine
    user: node
    networks:
      - app-net
    volumes:
      - ./client:/project
    ports:
      - 3000:3000
    working_dir: /project
    entrypoint: sh -c "yarn install && yarn start"
networks:
  app-net:
